name: Build & Release APK

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches: [master]
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create the release

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Restore keystore from secret
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > $GITHUB_WORKSPACE/app/keystore.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Signed Release APK
        env:
          KEYSTORE_FILE: keystore.jks
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file="$GITHUB_WORKSPACE/app/$KEYSTORE_FILE" \
            -Pandroid.injected.signing.store.password="${{ secrets.SIGNING_STORE_PASSWORD }}" \
            -Pandroid.injected.signing.key.alias="${{ secrets.SIGNING_KEY_ALIAS }}" \
            -Pandroid.injected.signing.key.password="${{ secrets.SIGNING_KEY_PASSWORD }}"

      - name: Generate Date Tag
        id: date_tag
        run: echo "VERSION_TAG=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.date_tag.outputs.VERSION_TAG }}
          name: Release v${{ steps.date_tag.outputs.VERSION_TAG }}
          draft: false
          prerelease: false
          files: app/build/outputs/apk/release/app-release.apk
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
